import { Service } from "../types";

export const services: Service[] = [
  {
    id: "1",
    title: "Phishing Simulation & Awareness",
    description:
      "Conduct realistic phishing campaigns to measure employee readiness and train staff with engaging awareness modules.",
    icon: "Shield",
    urlName: "phishing-simulation-awareness",
    detailedDescription:
      "Our comprehensive phishing simulation and awareness program helps organizations build a human firewall against cyber threats. We create realistic phishing campaigns that test your employees' ability to identify and respond to malicious emails, while providing engaging training modules to improve their cybersecurity awareness.",
    features: [
      "Realistic phishing email templates",
      "Customizable campaign scenarios",
      "Interactive training modules",
      "Detailed reporting and analytics",
      "Compliance tracking and documentation",
      "Multi-language support",
    ],
    benefits: [
      "Reduce phishing susceptibility by up to 90%",
      "Improve employee cybersecurity awareness",
      "Meet compliance requirements",
      "Reduce security incidents",
      "Build a security-conscious culture",
    ],
    useCases: [
      "Financial institutions protecting customer data",
      "Healthcare organizations securing patient information",
      "Government agencies preventing data breaches",
      "Educational institutions protecting student records",
      "Manufacturing companies securing intellectual property",
    ],
  },
  {
    id: "2",
    title: "Malware & Ransomware Simulation",
    description:
      "Safe, controlled attack simulations to test defenses and strengthen security posture.",
    icon: "Search",
    urlName: "malware-ransomware-simulation",
    detailedDescription:
      "Our malware and ransomware simulation services provide safe, controlled environments to test your organization's defenses against advanced persistent threats. We simulate real-world attack scenarios to identify vulnerabilities and strengthen your security posture without risking actual data loss.",
    features: [
      "Controlled malware deployment",
      "Ransomware simulation scenarios",
      "Endpoint detection testing",
      "Network segmentation validation",
      "Incident response testing",
      "Recovery procedure validation",
    ],
    benefits: [
      "Identify security gaps before attackers do",
      "Test incident response procedures",
      "Validate security tool effectiveness",
      "Improve team readiness",
      "Reduce recovery time",
    ],
    useCases: [
      "Testing endpoint protection platforms",
      "Validating backup and recovery systems",
      "Training security teams",
      "Compliance testing requirements",
      "Pre-deployment security validation",
    ],
  },
  {
    id: "3",
    title: "Website & Brand Protection",
    description:
      "Identify and remove malicious domains with dark web monitoring and quick takedowns.",
    icon: "Globe",
    urlName: "website-brand-protection",
    detailedDescription:
      "Protect your brand reputation and prevent customer fraud with our comprehensive website and brand protection services. We monitor the dark web, identify malicious domains, and provide rapid takedown services to protect your customers and maintain your brand integrity.",
    features: [
      "Dark web monitoring",
      "Domain takedown services",
      "Brand abuse detection",
      "Phishing site identification",
      "Social media monitoring",
      "Certificate monitoring",
    ],
    benefits: [
      "Protect customer trust and brand reputation",
      "Prevent financial losses from fraud",
      "Reduce customer support burden",
      "Maintain regulatory compliance",
      "Proactive threat detection",
    ],
    useCases: [
      "E-commerce platforms protecting customers",
      "Financial services preventing fraud",
      "Healthcare organizations protecting patients",
      "Government agencies securing citizens",
      "Educational institutions protecting students",
    ],
  },
  {
    id: "4",
    title: "Vulnerability Assessment Simulation",
    description:
      "Understanding the weaknesses in your IT infrastructure is the first step toward a strong cybersecurity posture. Our Vulnerability Assessment Simulation helps organizations identify, evaluate, and remediate potential security gaps before attackers can exploit them.",
    icon: "Network",
    urlName: "vulnerability-assessments",
    detailedDescription:
      "Understanding the weaknesses in your IT infrastructure is the first step toward a strong cybersecurity posture. Our Vulnerability Assessment Simulation helps organizations identify, evaluate, and remediate potential security gaps before attackers can exploit them.",
    features: [
      "Planning & Scoping – Define scope, critical assets, and assessment goals",
      "Discovery & Scanning – Identify vulnerabilities using automated tools and manual techniques",
      "Analysis & Risk Evaluation – Categorize vulnerabilities by severity and impact",
      "Reporting & Recommendations – Provide actionable remediation strategies",
      "Network vulnerability scanning",
      "Web application security testing",
      "Database security assessment",
      "Mobile application testing",
      "Cloud infrastructure scanning",
      "Compliance gap analysis",
    ],
    benefits: [
      "Proactively identify and fix vulnerabilities",
      "Reduce the risk of cyberattacks and data breaches",
      "Improve overall IT security and compliance",
      "Strengthen organizational cybersecurity readiness",
      "Detect vulnerabilities in networks, applications, and endpoints",
      "Assess the effectiveness of existing security controls",
      "Prioritize risks based on potential business impact",
    ],
    useCases: [
      "Pre-deployment security validation",
      "Regular security health checks",
      "Compliance audit preparation",
      "Merger and acquisition due diligence",
      "Third-party vendor assessment",
      "Software vulnerabilities: Outdated or unpatched software",
      "Configuration weaknesses: Misconfigured systems or applications",
      "Network vulnerabilities: Open ports, unsecured protocols, or weak network defenses",
      "Human vulnerabilities: Employees susceptible to phishing or social engineering attacks",
    ],
  },
  {
    id: "5",
    title: "24/7 Incident Response",
    description:
      "Cybersecurity incidents can occur at any time, putting your business at risk. Our 24/7 Incident Response services ensure that expert teams are available around the clock to detect, respond to, and mitigate cyber threats promptly.",
    icon: "Lock",
    urlName: "incident-response",
    detailedDescription:
      "Cybersecurity incidents can occur at any time, putting your business at risk. Our 24/7 Incident Response services ensure that expert teams are available around the clock to detect, respond to, and mitigate cyber threats promptly.",
    features: [
      "Continuous Monitoring – 24/7 monitoring of systems and networks to detect potential threats",
      "Threat Identification – Analyze alerts and logs to confirm security incidents",
      "Incident Containment – Take immediate actions to contain and prevent further damage",
      "Mitigation & Recovery – Remove threats, restore affected systems, and implement remediation measures",
      "Reporting & Recommendations – Provide detailed incident reports and guidance to prevent future occurrences",
      "24/7 incident response hotline",
      "Rapid containment procedures",
      "Digital forensics analysis",
      "Evidence preservation",
      "Recovery planning and execution",
      "Post-incident reporting",
    ],
    benefits: [
      "Minimize business disruption and financial losses",
      "Rapid response to cyber threats at any time",
      "Strengthen organizational resilience against attacks",
      "Maintain customer trust and regulatory compliance",
      "Rapid detection and containment of security incidents",
      "Minimize business impact and downtime",
      "Provide expert guidance for recovery and mitigation",
      "Ensure compliance with regulatory and industry standards",
    ],
    useCases: [
      "Ransomware attack response",
      "Data breach containment",
      "Malware outbreak management",
      "Insider threat investigation",
      "Advanced persistent threat response",
      "Continuous threat monitoring",
      "Emergency incident containment",
      "Business continuity during cyber attacks",
      "Regulatory compliance during incidents",
      "Customer communication during breaches",
    ],
  },
  {
    id: "6",
    title: "Cybersecurity Training",
    description:
      "SOC Analyst, Application Security, and Corporate Awareness training programs.",
    icon: "Cloud",
    urlName: "cybersecurity-training",
    detailedDescription:
      "Comprehensive cybersecurity training programs designed to build expertise across your organization. From technical SOC analyst training to executive awareness programs, we provide tailored education solutions that enhance your team's security capabilities.",
    features: [
      "SOC analyst certification programs",
      "Application security training",
      "Executive cybersecurity awareness",
      "Hands-on lab environments",
      "Certification exam preparation",
      "Custom training curricula",
    ],
    benefits: [
      "Build internal security expertise",
      "Reduce reliance on external consultants",
      "Improve security team effectiveness",
      "Meet compliance training requirements",
      "Foster security-conscious culture",
    ],
    useCases: [
      "Building internal SOC capabilities",
      "Developer security training",
      "Executive cybersecurity education",
      "Compliance training requirements",
      "Career development programs",
    ],
  },
];
