import { Service, TrainingProgram } from "../types";

export const services: Service[] = [
  {
    id: "1",
    title: "Phishing Simulation & Awareness",
    description:
      "Run safe, consent-first phishing campaigns and in-moment micro-training to measure vulnerability, improve reporting behavior, and reduce human risk.",
    icon: "Shield",
    urlName: "phishing-simulation-awareness",
    detailedDescription:
      "We design and run realistic but non-destructive phishing simulations tailored to your business (finance, HR, IT, executives). Each campaign is authorized, staged, and includes immediate, educational feedback for anyone who clicks — not punishment. Our goal is to make your people the strongest line of defense.",
    features: [
      "2,000+ realistic templates and industry scenarios",
      "Safe landing pages & learn-on-click micro-lessons",
      "Phish reporting integration with your mail client/SIEM",
      "Detailed analytics (click rate, report rate, repeat offenders, module completion)",
      "Role-specific templates (invoice lures, HR notices, IT alerts)",
      "On-click micro-training shown immediately (90–120 seconds)",
      "No credentials collected - safe simulation environment",
      "Custom templates crafted to match your environment",
    ],
    benefits: [
      "Reduce click rates by 40–75% over six months",
      "Improve reporting rates and shorten time-to-report",
      "Build human firewall against cyber threats",
      "Meet compliance requirements and standards",
      "Create security-conscious culture without punishment",
      "Measure vulnerability trends with detailed analytics",
      "Provide immediate educational feedback on clicks",
      "Deliver actionable insights and remediation plans",
    ],
    useCases: [
      "Financial institutions protecting customer data and preventing fraud",
      "Healthcare organizations securing patient information and HIPAA compliance",
      "Government agencies preventing data breaches and securing sensitive information",
      "Educational institutions protecting student records and research data",
      "Manufacturing companies securing intellectual property and trade secrets",
      "Technology companies protecting proprietary code and customer data",
      "Professional services maintaining client confidentiality",
      "E-commerce platforms protecting customer payment information",
    ],
    processFlow: [
      "Scope & Authorization — Document targets, timings, and get signed Rules of Engagement before any campaign",
      "Baseline Campaign — Run a low-risk test to measure current click and report rates",
      "Custom Templates — Use role-specific templates crafted to match your environment",
      "Simulate & Educate — On-click micro-training is shown immediately; no credentials are collected",
      "Report & Remediate — Deliver dashboards, per-user remediation plans, and executive summary",
    ],
    deliverables: [
      "Campaign plan & risk profile",
      "Custom email templates and safe landing pages",
      "Per-user remediation & training links",
      "Interactive dashboard and executive summary",
      "Optional quarterly repeat campaigns and continuous improvement support",
    ],
  },
  {
    id: "2",
    title: "Malware & Ransomware Simulation",
    description:
      "Safe, controlled attack simulations to test defenses and strengthen security posture.",
    icon: "Search",
    urlName: "malware-ransomware-simulation",
    detailedDescription:
      "Our malware and ransomware simulations are controlled, non-destructive exercises performed in isolated test environments to validate detection, containment, and recovery procedures — never to cause real harm. These simulations validate people, processes, and technology (EDR, backups, SIEM, incident response) so you can recover confidently if a real event occurs.",
    features: [
      "Non-destructive testing in isolated environments",
      "EICAR files and labeled dummy files for safe testing",
      "Benign beacon probes to internal sinkholes",
      "Synthetic data and staging network isolation",
      "Emergency stop procedures and kill switches",
      "Network sinkholes for simulated outbound traffic",
      "Real-time monitoring and evidence capture",
      "Comprehensive logging and packet capture",
    ],
    benefits: [
      "Test detection and alerting across EDR, network IDS, and SIEM",
      "Validate backup integrity and recovery procedures",
      "Practice incident response without production risk",
      "Improve playbooks and accelerate MTTD and MTTR",
      "Identify security gaps before attackers do",
      "Validate security tool effectiveness",
      "Improve team readiness and communication",
      "Reduce recovery time in real incidents",
    ],
    useCases: [
      "Testing endpoint protection platforms and EDR solutions",
      "Validating backup and recovery systems",
      "Training security teams and SOC analysts",
      "Compliance testing requirements and audits",
      "Pre-deployment security validation",
      "Incident response procedure testing",
      "Network segmentation validation",
      "SIEM tuning and optimization",
    ],
    processFlow: [
      "Authorization & ROE — Signed scope, approved IP ranges, target systems, test windows, and emergency stop procedures",
      "Environment & Hygiene — Use staging/isolated networks and synthetic data with network sinkholes",
      "Define Goals — Detection test, backup/resilience test, containment drill, or full IR table-top + live play",
      "Use benign, observable artifacts — EICAR files, labeled dummy files, and non-malicious beacon probes",
      "Execute & Monitor — Run simulation in controlled window while SOC/IR observe alerts, logs, and escalations",
      "Containment & Recovery Practice — Isolate affected hosts, run recovery from backups, follow communication playbooks",
      "After-Action Review — Produce forensic timeline, gaps & root cause, SIEM tuning recommendations, and remediation roadmap",
    ],
    scenarios: [
      "Detection of malicious file upload — Upload labeled test files to validate AV/EDR/WAF detection",
      "Beaconing / C2 lookalike — Benign agents make controlled GETs to internal sinkholes to validate network detection",
      "Ransomware response drill — Simulate file-encryption indicators using inert markers and verify backup and restore workflows",
      "Credential compromise play — Simulated account misuse using test accounts to validate IAM alerts and behavioral detections",
    ],
    measurements: [
      "Detection coverage across layers (endpoint, network, WAF)",
      "MTTD, MTTR, and time to isolate affected assets",
      "Backup integrity and time-to-restore",
      "SOC playbook execution quality and communications effectiveness",
    ],
    deliverables: [
      "Pre-test risk assessment & ROE document",
      "Test plan and expected indicators (IOCs) list (labeled test artifacts)",
      "Evidence package: WAF/EDR logs, SIEM incidents, packet captures, timeline",
      "Remediation roadmap: SIEM rule tuning, WAF rules, EDR policies, backup hardening",
      "After-action report and executive summary with recommended next steps",
    ],
  },
  {
    id: "3",
    title: "Website & Brand Protection",
    description:
      "Identify and remove malicious domains with dark web monitoring and quick takedowns.",
    icon: "Globe",
    urlName: "website-brand-protection",
    detailedDescription:
      "In today's digital landscape, protecting your brand and online presence is critical. Malicious domains, counterfeit websites, and dark web threats can damage reputation, revenue, and customer trust. Our Website & Brand Protection services help identify, monitor, and remove these threats before they impact your business.",
    features: [
      "Malicious Domain Identification - Detect unauthorized domains impersonating your brand",
      "Typosquatting Detection - Identify fraudulent websites targeting your customers",
      "Dark Web Monitoring - Continuously monitor dark web forums and underground channels",
      "Credential Leak Detection - Detect stolen credentials and leaked data",
      "Takedowns & Remediation - Initiate legal and technical takedown procedures",
      "Actionable Reporting - Provide insights and mitigation strategies",
      "24/7 Threat Monitoring - Real-time visibility of online threats",
      "Registrar Coordination - Work with registrars and hosting providers",
    ],
    benefits: [
      "Safeguard your brand reputation and customer trust",
      "Prevent financial losses from phishing, fraud, and counterfeit activities",
      "Gain real-time visibility of online threats targeting your organization",
      "Ensure compliance with security standards and regulatory requirements",
      "Reduce customer support burden from fraud-related inquiries",
      "Proactive threat detection and rapid response",
    ],
    useCases: [
      "E-commerce platforms protecting customers from fake websites",
      "Financial services preventing phishing attacks and fraud",
      "Healthcare organizations protecting patient data and reputation",
      "Government agencies securing citizens from malicious domains",
      "Educational institutions protecting students from credential theft",
      "Manufacturing companies protecting intellectual property",
      "Technology companies monitoring brand abuse and counterfeiting",
      "Professional services maintaining client trust and reputation",
    ],
  },
  {
    id: "4",
    title: "Vulnerability Assessment Simulation",
    description:
      "Understanding the weaknesses in your IT infrastructure is the first step toward a strong cybersecurity posture. Our Vulnerability Assessment Simulation helps organizations identify, evaluate, and remediate potential security gaps before attackers can exploit them.",
    icon: "Network",
    urlName: "vulnerability-assessments",
    detailedDescription:
      "Understanding the weaknesses in your IT infrastructure is the first step toward a strong cybersecurity posture. Our Vulnerability Assessment Simulation helps organizations identify, evaluate, and remediate potential security gaps before attackers can exploit them.",
    features: [
      "Planning & Scoping – Define scope, critical assets, and assessment goals",
      "Discovery & Scanning – Identify vulnerabilities using automated tools and manual techniques",
      "Analysis & Risk Evaluation – Categorize vulnerabilities by severity and impact",
      "Reporting & Recommendations – Provide actionable remediation strategies",
      "Network vulnerability scanning",
      "Web application security testing",
      "Database security assessment",
      "Mobile application testing",
      "Cloud infrastructure scanning",
      "Compliance gap analysis",
    ],
    benefits: [
      "Proactively identify and fix vulnerabilities",
      "Reduce the risk of cyberattacks and data breaches",
      "Improve overall IT security and compliance",
      "Strengthen organizational cybersecurity readiness",
      "Detect vulnerabilities in networks, applications, and endpoints",
      "Assess the effectiveness of existing security controls",
      "Prioritize risks based on potential business impact",
    ],
    useCases: [
      "Pre-deployment security validation",
      "Regular security health checks",
      "Compliance audit preparation",
      "Merger and acquisition due diligence",
      "Third-party vendor assessment",
      "Software vulnerabilities: Outdated or unpatched software",
      "Configuration weaknesses: Misconfigured systems or applications",
      "Network vulnerabilities: Open ports, unsecured protocols, or weak network defenses",
      "Human vulnerabilities: Employees susceptible to phishing or social engineering attacks",
    ],
  },
  {
    id: "5",
    title: "24/7 Incident Response",
    description:
      "Cybersecurity incidents can occur at any time, putting your business at risk. Our 24/7 Incident Response services ensure that expert teams are available around the clock to detect, respond to, and mitigate cyber threats promptly.",
    icon: "Lock",
    urlName: "incident-response",
    detailedDescription:
      "Cybersecurity incidents can occur at any time, putting your business at risk. Our 24/7 Incident Response services ensure that expert teams are available around the clock to detect, respond to, and mitigate cyber threats promptly.",
    features: [
      "Continuous Monitoring – 24/7 monitoring of systems and networks to detect potential threats",
      "Threat Identification – Analyze alerts and logs to confirm security incidents",
      "Incident Containment – Take immediate actions to contain and prevent further damage",
      "Mitigation & Recovery – Remove threats, restore affected systems, and implement remediation measures",
      "Reporting & Recommendations – Provide detailed incident reports and guidance to prevent future occurrences",
      "24/7 incident response hotline",
      "Rapid containment procedures",
      "Digital forensics analysis",
      "Evidence preservation",
      "Recovery planning and execution",
      "Post-incident reporting",
    ],
    benefits: [
      "Minimize business disruption and financial losses",
      "Rapid response to cyber threats at any time",
      "Strengthen organizational resilience against attacks",
      "Maintain customer trust and regulatory compliance",
      "Rapid detection and containment of security incidents",
      "Minimize business impact and downtime",
      "Provide expert guidance for recovery and mitigation",
      "Ensure compliance with regulatory and industry standards",
    ],
    useCases: [
      "Ransomware attack response",
      "Data breach containment",
      "Malware outbreak management",
      "Insider threat investigation",
      "Advanced persistent threat response",
      "Continuous threat monitoring",
      "Emergency incident containment",
      "Business continuity during cyber attacks",
      "Regulatory compliance during incidents",
      "Customer communication during breaches",
    ],
  },
  {
    id: "6",
    title: "Cybersecurity Training",
    description:
      "SOC Analyst, Application Security, and Corporate Awareness training programs.",
    icon: "Cloud",
    urlName: "cybersecurity-training",
    detailedDescription:
      "Comprehensive cybersecurity training programs designed to build expertise across your organization. From technical SOC analyst training to executive awareness programs, we provide tailored education solutions that enhance your team's security capabilities.",
    features: [
      "SOC analyst certification programs",
      "Application security training",
      "Executive cybersecurity awareness",
      "Hands-on lab environments",
      "Certification exam preparation",
      "Custom training curricula",
    ],
    benefits: [
      "Build internal security expertise",
      "Reduce reliance on external consultants",
      "Improve security team effectiveness",
      "Meet compliance training requirements",
      "Foster security-conscious culture",
    ],
    useCases: [
      "Building internal SOC capabilities",
      "Developer security training",
      "Executive cybersecurity education",
      "Compliance training requirements",
      "Career development programs",
    ],
  },
];

export const trainingPrograms: TrainingProgram[] = [
  {
    id: "1",
    title: "SOC Analyst Certification",
    description:
      "Comprehensive training program for Security Operations Center analysts covering threat detection, incident response, and security monitoring.",
    icon: "Shield",
    duration: "40 hours",
    level: "Intermediate",
    features: [
      "Hands-on SIEM training",
      "Threat hunting techniques",
      "Incident response procedures",
      "Log analysis and correlation",
      "Security tool operation",
      "Certification exam preparation",
    ],
    benefits: [
      "Industry-recognized certification",
      "Practical hands-on experience",
      "Career advancement opportunities",
      "Enhanced security skills",
      "Better job market prospects",
    ],
  },
  {
    id: "2",
    title: "Application Security Training",
    description:
      "Learn secure coding practices, vulnerability assessment, and application security testing methodologies.",
    icon: "Search",
    duration: "32 hours",
    level: "Advanced",
    features: [
      "Secure coding principles",
      "OWASP Top 10 vulnerabilities",
      "Static and dynamic testing",
      "Code review techniques",
      "Security testing tools",
      "DevSecOps integration",
    ],
    benefits: [
      "Build secure applications",
      "Reduce security vulnerabilities",
      "Comply with security standards",
      "Integrate security in SDLC",
      "Prevent common attack vectors",
    ],
  },
  {
    id: "3",
    title: "Executive Cybersecurity Awareness",
    description:
      "Strategic cybersecurity training for executives and decision-makers covering risk management and governance.",
    icon: "Network",
    duration: "16 hours",
    level: "Beginner",
    features: [
      "Cybersecurity risk assessment",
      "Regulatory compliance overview",
      "Incident response planning",
      "Security governance frameworks",
      "Budget planning for security",
      "Vendor risk management",
    ],
    benefits: [
      "Make informed security decisions",
      "Understand business risks",
      "Comply with regulations",
      "Protect organizational assets",
      "Lead security initiatives",
    ],
  },
  {
    id: "4",
    title: "Penetration Testing Fundamentals",
    description:
      "Learn ethical hacking techniques, vulnerability assessment, and penetration testing methodologies.",
    icon: "Lock",
    duration: "48 hours",
    level: "Advanced",
    features: [
      "Network penetration testing",
      "Web application testing",
      "Social engineering techniques",
      "Wireless security testing",
      "Report writing and documentation",
      "Legal and ethical considerations",
    ],
    benefits: [
      "Identify security weaknesses",
      "Conduct professional assessments",
      "Improve security posture",
      "Career in ethical hacking",
      "Certified ethical hacker preparation",
    ],
  },
  {
    id: "5",
    title: "Cloud Security Training",
    description:
      "Comprehensive cloud security training covering AWS, Azure, and GCP security best practices.",
    icon: "Cloud",
    duration: "36 hours",
    level: "Intermediate",
    features: [
      "Cloud security architecture",
      "Identity and access management",
      "Data protection in cloud",
      "Compliance and governance",
      "Security monitoring and logging",
      "Incident response in cloud",
    ],
    benefits: [
      "Secure cloud deployments",
      "Understand cloud risks",
      "Implement security controls",
      "Comply with cloud regulations",
      "Career in cloud security",
    ],
  },
  {
    id: "6",
    title: "Incident Response Training",
    description:
      "Learn effective incident response procedures, digital forensics, and crisis management.",
    icon: "Globe",
    duration: "24 hours",
    level: "Intermediate",
    features: [
      "Incident response planning",
      "Digital forensics basics",
      "Evidence collection and preservation",
      "Communication during incidents",
      "Recovery procedures",
      "Post-incident analysis",
    ],
    benefits: [
      "Respond effectively to incidents",
      "Minimize business impact",
      "Preserve evidence properly",
      "Improve recovery time",
      "Build incident response capabilities",
    ],
  },
];
